### ISSUE TITLE
No drill-down effect in Viewer sidebar filters

### ISSUE THREAD

**Issue by cyberbikepunk** [os-data/mexican-federal-budget#2]
The issue is that filters don't reduce their scope when a parent dimension is already selected. For example if you filter by `Gobierno` in `Grupo Funcional` you’ll still see `Function` items of other `Grupo Funcional` items. Intuitively, you should only see `Gobierno` items. 

This issue was pointed out from the beginning, as the user wouldn’t know what categories exist within each category. It's been [already filed in the Open-Spending repository](https://github.com/openspending/openspending/issues/1025).  As for now, is been **closed**  as a `wontfix`. My question is _why_?

**Comment by akariv** [comment]
The reason is that filters are used to slice the data, not for navigation.

When selecting a drilldown-able visualisation, you must choose a hierarchy. Then the filtering is correctly managed by the navigation controls. This means that grouping and filtering columns are selected correctly based on the level in the current hierarchy.

This is the reason that the filters that belong to the selected hierarchy will not appear in the filter list - when (for example) you select the "functional classification" hierarchy, its filters do not appear in the list, as can be seen here http://next.openspending.org/viewer/5df4a7b06a940c992d1c44525daff47b:mex?lang=en&measure=Adefas.sum&groups%5B%5D=functional_classification_2.Grupo_Funcional&order=Adefas.sum%7Cdesc&visualizations%5B%5D=Treemap
