### ISSUE TITLE
Wrong column name: PP should be ID_PP

### ISSUE THREAD

**Issue by cyberbikepunk** [os-data/mexican-federal-budget#42]
The dataset uploaded for launch has a bug in the column name. @Victordeleon do we want to fix that? This would make the dataset backwards incompatible.

**Comment by Victordeleon** [comment]
Hey @cyberbikepunk I'm not sure if I understand what you meand with backwards incompatible, Is it that the data base won't be comparable with the previous one we've uploade? If that's the case then I think we should fix it, since our interest is that we can make the data base compatible with the future versions that will be uploaded. 

Besides of ID_PP I haven't seen changes in the rest of the backend headers we marked as yellow, please let me know if you need any help.

**Comment by cyberbikepunk** [comment]
Solved in pipeline run 19.
