### ISSUE TITLE
Pivot tables problems

### ISSUE THREAD

**Issue by cyberbikepunk** [os-data/mexican-federal-budget#7]
Quoting Aura:

> When you choose your visualization to be a **Pivot Table** the `Modalidad del Programa Presupuestario` always appears at the rows, no matter if it´s filter hasn’t been selected. Also, the Pivot Table only allows you to choose one option per filter. It would be better if you can choose more than one so you can compare information. 

![pivot_table_fail](https://cloud.githubusercontent.com/assets/1629834/18003506/3f17c052-6b8e-11e6-8b4f-6ee4af4b0700.png)

**Comment by cyberbikepunk** [comment]
Could Aura or Victor please provide us with a screenplay of what they are trying to do? Or at the minimum a viewer-link with a description of where they click next?

**Comment by Victordeleon** [comment]
Hi @cyberbikepunk 

So I was revising this and seems as there have been changes, because I can't reproduce it exactly as I remember. Right now I can control the rows by selecting an option in "X-Axis" and I don´t seem to have control over the columns, which seem to be automatically selected from the available "Measures"(I can select several options from the "Series" which doesn't seem to have any kind of efect over the pivot table).

I also was able to filter the table by more than one option. So I only have two questions left:
1. Is it correct that I can select options from "Series" without having any efect in the pivot table or I´m getting it wrong, wouldn't it be for controlling the columns in the pivot table and the "Measures for selecting the value of the cells?; and 
2. What happened to the download CSV option? It should be available to downlad the selected table. 

So I´ll add a reproduction, where:
- Measures = "Aprobado".
- X-axis = "Ramo".
- Series = "Modalidad del Programa Presupuestario", "Ramo", "Unidad Responsable", "Ciclo" and "Descripción del Tipo de Gasto". 
  -Filters = "Grupo funcional - Desarrollo Social", "Ciclo - 2016". 

You can check it in the following link.

http://next.openspending.org:80/viewer/embed/table/5df4a7b06a940c992d1c44525daff47b:mex-restructured?lang=en&measure=Aprobado.sum&groups[]=administrative_classification_2.Ramo&series[]=activity_Modalidad_del.Modalidad_del_Programa&series[]=administrative_classification_2.Ramo&series[]=administrative_classification_3.Unidad_Responsable&series[]=date_2.Ciclo&series[]=expenditure_type_2.Descripcion_de_Tipo_de_Gasto&filters[]=date_2.Ciclo|2016&filters[]=functional_classification_2.Grupo_Funcional|2&order=administrative_classification_2.Ramo|desc
